// src/content/blog/reactivity/solid/example2.tsx
/** @jsxImportSource solid-js */
import { createResource, createSignal, Suspense } from "solid-js";

async function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(() => resolve(ms), ms));
}

async function divide(a: number, b: number) {
  await sleep(200 + Math.random() * 1000);
  return a / b;
}

export function SolidExample2() {
  const [n, setN] = createSignal(1);
  const [data] = createResource(n, async (n) => {
    const result = await divide(n, 5);
    return { result, n };
  });

  return (
    <div>
      <div>n = {n()}</div>
      <button type="button" onClick={() => setN((prev) => prev + 1)}>
        Increment
      </button>
      <Suspense fallback={<div>Loading...</div>}>
        <div style={{ opacity: data.loading ? 0.8 : 1 }}>
          {data.latest?.n} / 5 = {data.latest?.result?.toFixed(3)}
        </div>
      </Suspense>
    </div>
  );
}

// src/content/blog/reactivity/react/example2.tsx
import { useCallback, useEffect, useState } from "react";

async function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(() => resolve(ms), ms));
}

async function divide(a: number, b: number) {
  await sleep(200 + Math.random() * 1000);
  return a / b;
}

export function ReactExample2() {
  const [nLatest, setNLatest] = useState(1);
  const increment = useCallback(() => setNLatest((prev) => prev + 1), []);
  const [n, setN] = useState(nLatest);

  const [data, setData] = useState<number | undefined>(undefined);
  const [isPending, setIsPending] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setIsPending(true);
    divide(nLatest, 5).then((result) => {
      if (cancelled) {
        return;
      }
      setData(result);
      setIsPending(false);
      setN(nLatest);
    });

    return () => {
      cancelled = true;
    };
  }, [nLatest]);

  return (
    <div>
      <div>n = {nLatest}</div>
      <button type="button" onClick={increment}>
        Increment
      </button>
      {data === undefined ? (
        <div>loading...</div>
      ) : (
        <div style={{ opacity: isPending ? 0.5 : 1 }}>
          {n} / 5 = {data.toFixed(3)}
        </div>
      )}
    </div>
  );
}
